### ISSUE TITLE
Support API of Harbor 2.x

### ISSUE THREAD

**Issue by solidnerd** [nolte/terraform-provider-harbor#7]
**Describe the feature**

The current  supported version of Harbor from the provider is `1.10.2` . To be compatible for the future we should start with the implementation of new [released Harbor](https://github.com/goharbor/harbor/releases/latest) `2.0.0` version. 

At the moment it's only testable via an VM Setup currently there is no helm chart with harbor 2.0

There is some changing stuff in harbor:

* Breaking change in API: Most of the REST APIs now has the prefix /api/v2.0 in the URI, instead of /api. For details please refer to the following API docs:
https://github.com/goharbor/harbor/blob/release-2.0.0/api/v2.0/legacy_swagger.yaml
https://github.com/goharbor/harbor/blob/release-2.0.0/api/v2.0/swagger.yaml
https://github.com/goharbor/harbor/blob/release-2.0.0/api/swagger.yaml

**Additional context**

**Comment by nolte** [comment]
Hi,
I think, most of the ressources are v2 ready, The Base [Acception Test](https://github.com/nolte/terraform-provider-harbor/blob/develop/scripts/test/tf-acception-test/main.tf#L13) runs by default again the [demo.goharbor.io](https://demo.goharbor.io) instance, version 2.1.0.
